server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb?serverTimezone=GMT
    username: root
    password: a1471689575
    driver-class-name: com.mysql.cj.jdbc.Driver
#    连接池配置
    hikari:
#      最小空闲数
      minimum-idle: 0
#      最大连接数
      maximum-pool-size: 10
      idle-timeout: 180000
  resources:
    static-locations: classpath:/static/
  redis:
    port: 6379
    password:
    database: 0
    timeout: 2000
    lettuce:
      pool:
        max-wait: 1
        max-active: 8
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
    host: 127.0.0.1
  cache:
    type: redis
# 配置mybatis-plus中的对应mapper类
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
# 配置redis连接的数据库
redis:
  database:
    login: 1
    token: 2
